"use client";

import * as React from "react";
import { ShieldAlertIcon, KeyIcon, Loader2Icon, ArrowRightIcon } from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/shared/ui/dialog";
import { Button } from "@/shared/ui/button";
import { Input } from "@/shared/ui/input";
import { Label } from "@/shared/ui/label";

interface TwoFactorModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onSuccess: () => void;
}

export function TwoFactorModal({
  open,
  onOpenChange,
  onSuccess,
}: TwoFactorModalProps) {
  const [code, setCode] = React.useState("");
  const [isVerifying, setIsVerifying] = React.useState(false);
  const [error, setError] = React.useState<string | null>(null);
  const [useBackupCode, setUseBackupCode] = React.useState(false);

  const handleVerify = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!code || code.length < 6) {
      setError("Please provide a valid 6-digit verification code.");
      return;
    }

    setIsVerifying(true);
    setError(null);

    try {
      // Mock / actual verification
      await new Promise((resolve) => setTimeout(resolve, 800));
      onSuccess();
    } catch {
      setError("Invalid authenticator code. Check your device clock or use a backup code.");
    } finally {
      setIsVerifying(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-md border-border/80 bg-card shadow-none">
        <DialogHeader>
          <div className="flex size-10 items-center justify-center rounded-xl bg-primary/10 text-primary mb-2">
            <ShieldAlertIcon className="size-5" />
          </div>
          <DialogTitle>Two-Factor Authentication Required</DialogTitle>
          <DialogDescription className="text-xs leading-relaxed">
            Enter the 6-digit security code generated by your hardware authenticator or TOTP app (Google Authenticator, 1Password, or YubiKey).
          </DialogDescription>
        </DialogHeader>

        <form onSubmit={handleVerify} className="space-y-4 py-2">
          {error && (
            <div className="rounded-lg border border-destructive/30 bg-destructive/10 p-2.5 text-xs text-destructive">
              {error}
            </div>
          )}

          <div className="space-y-1.5">
            <Label htmlFor="2fa-code" className="text-xs font-medium">
              {useBackupCode ? "8-Character Backup Code" : "6-Digit Authenticator Code"}
            </Label>
            <Input
              id="2fa-code"
              type="text"
              value={code}
              onChange={(e) => setCode(e.target.value.replace(/\s+/g, ""))}
              placeholder={useBackupCode ? "ABCD-1234" : "123456"}
              maxLength={useBackupCode ? 10 : 6}
              className="text-center font-mono text-lg tracking-widest"
              autoFocus
              required
            />
          </div>

          <div className="flex justify-between items-center text-xs text-muted-foreground pt-1">
            <button
              type="button"
              onClick={() => {
                setUseBackupCode(!useBackupCode);
                setCode("");
                setError(null);
              }}
              className="text-primary hover:underline flex items-center gap-1"
            >
              <KeyIcon className="size-3" />
              {useBackupCode ? "Use Authenticator App" : "Use Emergency Backup Code"}
            </button>
            <span>Time-synced TOTP</span>
          </div>

          <DialogFooter className="pt-2">
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={() => onOpenChange(false)}
            >
              Cancel
            </Button>
            <Button
              type="submit"
              size="sm"
              disabled={isVerifying}
              className="gap-1.5"
            >
              {isVerifying ? (
                <>
                  <Loader2Icon className="size-3.5 animate-spin" />
                  Verifying...
                </>
              ) : (
                <>
                  Verify Code
                  <ArrowRightIcon className="size-3.5" />
                </>
              )}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}
